# Hybrid Edge Detection + LBP + Reversible LSB Steganography Configuration
# This file contains all parameters for the steganography system

# Edge Detection Parameters
edge_detection:
  # Thresholds for different edge detection methods
  canny:
    low_threshold: 50
    high_threshold: 150
    kernel_size: 3
  
  sobel:
    kernel_size: 3
    scale: 1
    delta: 0
  
  prewitt:
    kernel_size: 3
  
  kirsch:
    kernel_size: 3
  
  laplacian_of_gaussian:
    sigma: 1.0
    kernel_size: 5
  
  # Combined edge detection settings
  combination:
    weights:
      canny: 0.3
      sobel: 0.2
      prewitt: 0.2
      kirsch: 0.15
      log: 0.15
    threshold: 0.3  # Threshold for final edge mask

# Local Binary Pattern (LBP) Parameters
lbp:
  radius: 1
  n_points: 8
  method: "uniform"  # Options: uniform, default, ror, var
  texture_threshold: 0.4

# Pixel Selection Parameters
pixel_selection:
  # Maximum percentage of image pixels to use for embedding
  max_capacity_ratio: 0.1  # 10% of total pixels
  
  # Minimum capacity ratio to maintain
  min_capacity_ratio: 0.05  # 5% of total pixels
  
  # Selection strategy
  strategy: "edge_and_texture"  # Options: edge_and_texture, edge_or_texture, texture_only, edge_only
  
  # Adaptive threshold optimization
  adaptive_threshold:
    enabled: true
    target_psnr: 40.0
    max_iterations: 10
    edge_threshold_range: [0.2, 0.6]
    texture_threshold_range: [0.3, 0.7]
    capacity_ratio_range: [0.05, 0.15]

# LSB Embedding Parameters
embedding:
  # Channel selection for color images
  color_channel: 0  # 0=Blue, 1=Green, 2=Red (Blue is least perceptible)
  
  # Embedding pattern
  pattern: "sequential"  # Options: sequential, random, spiral
  
  # Metadata handling
  add_metadata_header: true
  
  # Payload preprocessing
  payload:
    auto_detect_type: true
    supported_text_extensions: [".txt", ".md", ".json"]
    supported_image_extensions: [".png", ".jpg", ".jpeg", ".bmp", ".tiff"]
    max_payload_size_mb: 10

# Quality Control Parameters
quality:
  # Minimum acceptable quality metrics
  min_psnr: 30.0
  min_ssim: 0.9
  min_correlation: 0.95
  
  # Target quality metrics for optimization
  target_psnr: 40.0
  target_ssim: 0.95
  target_correlation: 0.98
  
  # Quality assessment thresholds
  quality_levels:
    excellent:
      psnr: 45
      ssim: 0.98
      correlation: 0.99
    good:
      psnr: 35
      ssim: 0.95
      correlation: 0.95
    acceptable:
      psnr: 25
      ssim: 0.90
      correlation: 0.90
    poor:
      psnr: 15
      ssim: 0.80
      correlation: 0.80

# Reversibility Parameters
reversibility:
  # Trace matrix settings
  save_trace_matrix: true
  compress_trace_matrix: false
  
  # Verification settings
  verify_restoration: true
  tolerance: 0  # Zero tolerance for perfect reversibility
  
  # Security settings (for future implementation)
  password_protection: false
  encryption_algorithm: "AES256"

# Evaluation Parameters
evaluation:
  # Metrics to calculate
  metrics:
    basic: ["psnr", "ssim", "mse", "mae"]
    advanced: ["snr", "uqi", "entropy", "correlation"]
    histogram: ["correlation", "intersection", "bhattacharyya", "kl_divergence"]
    reversibility: ["perfect_restoration", "lossless_restoration"]
  
  # Visualization settings
  create_plots: true
  plot_formats: ["png", "pdf"]
  plot_dpi: 300
  
  # Report settings
  save_json_report: true
  save_detailed_report: true
  include_recommendations: true

# Application-Specific Settings
applications:
  # Medical imaging settings
  medical:
    max_capacity_ratio: 0.05  # Conservative for medical data
    min_psnr: 45.0
    min_ssim: 0.98
    edge_threshold: 0.4
    texture_threshold: 0.5
  
  # Forensic imaging settings
  forensic:
    max_capacity_ratio: 0.08
    min_psnr: 40.0
    min_ssim: 0.95
    edge_threshold: 0.35
    texture_threshold: 0.45
  
  # E-government settings
  e_government:
    max_capacity_ratio: 0.1
    min_psnr: 35.0
    min_ssim: 0.92
    edge_threshold: 0.3
    texture_threshold: 0.4

# Preprocessing Parameters
preprocessing:
  # Image normalization
  normalize_images: true
  normalization_range: [0, 255]
  
  # Noise reduction (optional)
  apply_denoising: false
  denoising_method: "gaussian"  # Options: gaussian, bilateral, median
  
  # Image enhancement (optional)
  apply_enhancement: false
  enhancement_method: "histogram_equalization"

# Performance Parameters
performance:
  # Parallel processing
  use_multiprocessing: false
  max_workers: 4
  
  # Memory management
  max_image_size_mb: 100
  chunk_processing: false
  chunk_size: 1024
  
  # Progress tracking
  show_progress: true
  progress_update_interval: 0.1  # seconds

# Logging Parameters
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_to_file: true
  log_file_path: "logs/steganography.log"
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_log_size_mb: 10
  backup_count: 5

# Development and Testing Parameters
development:
  # Debug settings
  debug_mode: false
  save_intermediate_results: false
  intermediate_results_dir: "debug/"
  
  # Testing settings
  run_unit_tests: false
  test_data_dir: "test_data/"
  
  # Validation settings
  validate_inputs: true
  strict_mode: false